CREATE TABLE SOCS (
    ID SERIAL,
    NOMBRE VARCHAR(100) NOT NULL,
    PAIS VARCHAR(100) NOT NULL,
    NIVEL_SEGURIDAD INT NOT NULL,
    AUTOR_EXAMEN VARCHAR(100) NOT NULL,

    CONSTRAINT PK_SOCS PRIMARY KEY (ID)
);

CREATE TABLE INCIDENTES (
    ID SERIAL PRIMARY KEY,
    CODIGO_INCIDENTE VARCHAR(100) NOT NULL,
    TIPO_INCIDENTE VARCHAR(100) NOT NULL,
    FECHA_DETECCION VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(100) NOT NULL,
    AUTOR_EXAMEN VARCHAR(100) NOT NULL,
    FK_SOC_ID INT NOT NULL,

    CONSTRAINT FK_INCIDENTE_SOC_ID FOREIGN KEY (FK_SOC_ID) REFERENCES SOCS (ID)
);

CREATE TABLE INFORMES_INCIDENTE (
    ID SERIAL PRIMARY KEY,
    MALWARE_DETECTADO VARCHAR(100) NOT NULL,
    NIVEL_SEVERIDAD INT NOT NULL,
    CONCLUSION VARCHAR(250) NOT NULL,
    AUTOR_EXAMEN VARCHAR(100) NOT NULL,
    FK_INCIDENTE_ID INT NOT NULL,

    CONSTRAINT FK_INFORMES_INCIDENTE_INCIDENTES_ID FOREIGN KEY (FK_INCIDENTE_ID) REFERENCES INCIDENTES (ID),
    CONSTRAINT UQ_INFORMES_INCIDENTE UNIQUE (FK_INCIDENTE_ID)
);