CREATE TABLE SOCS (
    ID SERIAL,
    NOMBRE VARCHAR(100) NOT NULL,
    PAIS VARCHAR(100) NOT NULL,
    NIVEL_SEGURIDAD INT NOT NULL,
    AUTOR_EXAMEN VARCHAR(100) NOT NULL,

    CONSTRAINT PK_SOCS PRIMARY KEY (ID)
);

CREATE TABLE INCIDENTES (
    ID SERIAL PRIMARY KEY,
    CODIGO_INCIDENTE VARCHAR(100) NOT NULL,
    TIPO_INCIDENTE VARCHAR(100) NOT NULL,
    FECHA_DETECCION VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(100) NOT NULL,
    AUTOR_EXAMEN VARCHAR(100) NOT NULL,
    FK_SOC_ID INT NOT NULL,

    CONSTRAINT FK_INCIDENTE_SOC_ID FOREIGN KEY (FK_SOC_ID) REFERENCES SOCS (ID)
);

CREATE TABLE INFORMES_INCIDENTE (
    ID SERIAL PRIMARY KEY,
    MALWARE_DETECTADO VARCHAR(100) NOT NULL,
    NIVEL_SEVERIDAD INT NOT NULL,
    CONCLUSION VARCHAR(250) NOT NULL,
    AUTOR_EXAMEN VARCHAR(100) NOT NULL,
    FK_INCIDENTE_ID INT NOT NULL,

    CONSTRAINT FK_INFORMES_INCIDENTE_INCIDENTES_ID FOREIGN KEY (FK_INCIDENTE_ID) REFERENCES INCIDENTES (ID),
    CONSTRAINT UQ_INFORMES_INCIDENTE UNIQUE (FK_INCIDENTE_ID)
);


INSERT INTO SOCS VALUES (1, 'SOC1', 'ESPAÑA', 9, 'DIEGO JUSTO');
INSERT INTO SOCS VALUES (2, 'SOC2', 'FRANCIA', 6, 'DIEGO JUSTO');
INSERT INTO SOCS VALUES (3, 'SOC3', 'ESPAÑA', 7, 'DIEGO JUSTO');
INSERT INTO SOCS VALUES (4, 'SOC4', 'ITALIA', 7, 'DIEGO JUSTO');
INSERT INTO SOCS VALUES (5, 'SOC5', 'ESPAÑA', 8, 'DIEGO JUSTO');

INSERT INTO INCIDENTES VALUES (1, '1233C', 'ESPAÑA', 20/01/2025, 'ARCHIVADO', 'DIEGO JUSTO', 2);
INSERT INTO INCIDENTES VALUES (2, '1245X', 'FRANCIA', 07/04/2025, 'ACTIVO', 'DIEGO JUSTO', 3);
INSERT INTO INCIDENTES VALUES (3, '2122A', 'ESPAÑA', 11/02/2025, 'ARCHIVADO', 'DIEGO JUSTO', 1);
INSERT INTO INCIDENTES VALUES (4, '1652B', 'ITALIA', 29/07/2025, 'ACTIVO', 'DIEGO JUSTO', 2);
INSERT INTO INCIDENTES VALUES (5, '1892F', 'ESPAÑA', 17/01/2026, 'ARCHIVADO', 'DIEGO JUSTO', 1);

INSERT INTO INFORMES_INCIDENTE VALUES (1, 'NO', 9, 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 'DIEGO JUSTO', 1);
INSERT INTO INFORMES_INCIDENTE VALUES (2, 'NO', 8, 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB', 'DIEGO JUSTO', 2);
INSERT INTO INFORMES_INCIDENTE VALUES (3, 'NO', 5, 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC', 'DIEGO JUSTO', 3);
INSERT INTO INFORMES_INCIDENTE VALUES (4, 'NO', 6, 'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD', 'DIEGO JUSTO', 4);
INSERT INTO INFORMES_INCIDENTE VALUES (5, 'NO', 7, 'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE', 'DIEGO JUSTO', 5);